/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class www_seven_com_ndklib_MyNdkLib */

#ifndef _Included_www_seven_com_ndklib_MyNdkLib
#define _Included_www_seven_com_ndklib_MyNdkLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     www_seven_com_ndklib_MyNdkLib
 * Method:    getHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_www_seven_com_ndklib_MyNdkLib_getHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
